n1 = float(input('Insira um número: '))
n2 = float(input('Insira outro número: '))
n3 = float(input('Insira mais um número; '))
print('O maior número é: {}'.format(max(n1,n2,n3)))
print('O Menor número é: {}'.format(min(n1,n2,n3)))
